# Generated by Django 4.1.4 on 2024-02-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snakemodel",
            name="gamename",
            field=models.CharField(default="snake game", max_length=15),
        ),
    ]
