# Generated by Django 4.1.4 on 2024-03-01 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0003_rename_snake_highscore_snakemodel_highscore_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShooterGameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gamename",
                    models.CharField(default="Astroid shooter", max_length=15),
                ),
                ("score", models.IntegerField()),
                ("highscore", models.IntegerField()),
                ("totalscore", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
